title: Muhammad Ayaz, PhD
description: Economist | Development | Agricultural | Environmental Economics
theme: minima

author:
 name: Muhammad Ayaz,PhD

  email: m.ayaz@univ-pau.fr   and ayaznasar@gmail.com | 🌐 [Google Scholar](https://scholar.google.fr/citations?user=vDB0ClQAAAAJ) | 📄 [HAL](https://hal.science/984215) | 💼 [LinkedIn](https://www.linkedin.com/in/ayaz-khan-12b0b780)


header_pages:
  - cv.md
  - publications.md
  - conferences.md
  - research.md
  - teaching.md
  - awards.md
  

show_excerpts: true
