title: **Muhammad AYAZ, PhD**
description: Economist | Development | Agricultural | Environmental Economics
theme: minima

author:
  name: Muhammad Ayaz, PhD
  email: m.ayaz@univ-pau.fr

header_pages:
  - cv.md
  - publications.md
  - conferences.md
  - research.md
  - teaching.md
  - awards.md

show_excerpts: true
