title: Muhammad Ayaz, PhD
description: Economist | Development & Agricultural Economics
theme: minima

author:
  name: Muhammad Ayaz
  email: m.ayaz@univ-pau.fr   and ayaznasar@gmail.com

header_pages:
  - cv.md
  - publications.md

markdown: kramdown
